### ISSUE TITLE
Drop–down's panel needs some logic to keep it within the visible viewport

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#199] opened 2017-04-10 17:35 UTC
This is quite a problem in case of the inline editor:

![apr-10-2017 19-34-07](https://cloud.githubusercontent.com/assets/156149/24874408/d205efd0-1e24-11e7-9533-5101cf622b68.gif)

**Comment by oleq** [comment] 2017-04-18 12:45
It's a must–have feature, given that it works in v4 
![image](https://cloud.githubusercontent.com/assets/1099479/25131349/a3f11e7c-2445-11e7-98d8-7e33e7122710.png)

**Comment by Mgsy** [comment] 2017-10-10 14:54
It seems that this one doesn't occur anymore. If you can confirm that, I believe we can close this issue.

![bug_cke5](https://user-images.githubusercontent.com/20988892/31393223-8686fb3e-addb-11e7-939a-dad5b055a708.gif)

**Comment by oleq** [comment] 2017-10-13 12:41
@Mgsy, the issue is all about "at the bottom of the viewport". So I'm afraid it is still valid because we didn't address this kind of issue anywhere.

**Comment by Mgsy** [comment] 2017-10-13 12:53
> @Mgsy, the issue is all about "at the bottom of the viewport". So I'm afraid it is still valid because we didn't address this kind of issue anywhere.

Yes, you're right, I missed the `bottom of the viewport` part. Thanks for the explanation.

**Comment by oleq** [comment] 2018-02-27 09:02
Related issue https://github.com/ckeditor/ckeditor5-ui/issues/123.

**Comment by oleq** [comment] 2018-06-19 10:55
Another case
<img width="848" alt="screen shot 2018-06-19 at 12 54 50" src="https://user-images.githubusercontent.com/1099479/41593332-f8cb23be-73bf-11e8-825d-fa7b8c5b8c2f.png">

**Comment by oleq** [comment] 2018-10-16 14:01
I believe this has been resolved in https://github.com/ckeditor/ckeditor5-ui/issues/123.

**Closed by oleq** 2018-10-16 14:01 UTC
Labels: candidate:backlog, status:confirmed, type:bug
