### ISSUE TITLE
ContextualToolbar is attached to nothing when editable is not focused

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui#257] opened 2017-06-22 12:48 UTC
ATM `CT` is visible as long as [the entire editor is focused](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/toolbar/contextual/contextualtoolbar.js#L105-L108).

![jun-22-2017 14-42-03](https://user-images.githubusercontent.com/1057056/27434421-f2b9e2d2-5758-11e7-95e9-1ee2537c6ab8.gif)

I think it will be better to keep `CT` visible only as long as `ViewDocument` will be focused. WDYT?

**Comment by Reinmar** [comment] 2017-06-22 13:13
I agree. CT should disappear as soon the focus manager says "blurred". Checking `ViewDocument`'s focus only will be too narrow, I think, because once you moved focus to the toolbar it will disappear ;)

**Comment by oskarwrobel** [comment] 2017-06-22 13:24
> CT should disappear as soon the focus manager says "blurred"

That's how it works now and this is the problem. When you move focus to the toolbar (in my example Editor UI element) selection will disappear because viewDoc will be blurred, but `FT` will stay focused.

**Comment by Reinmar** [comment] 2017-06-22 13:47
So that's a completely different issue :) It's that the selection disappears when editable loses focus. We've got an issue for that somewhere... in the link package I think: https://github.com/ckeditor/ckeditor5-link/issues/13.

Do you confirm that it's it?

**Comment by oskarwrobel** [comment] 2017-06-22 14:00
Yep, something like fake selection should solve it.

**Comment by Reinmar** [comment] 2017-06-22 14:04
So, let's make it a duplicate of https://github.com/ckeditor/ckeditor5-engine/issues/976.

**Closed** 2017-06-22 14:03 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
